import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
  },
  regItemsContainer: {
    backgroundColor: "white",
    flex: 5,
    width: "100%",
    alignItems: "center",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    gap: 16,
  },
  regTextInput: {
    width: "90%",
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: "#F6F6F6",
    borderColor: "#E8E8E8",
    height: 50,
    paddingLeft: 16,
  },
  regButton: {
    backgroundColor: "#FF6C00",
    borderRadius: 100,
    width: "90%",
    paddingVertical: 16,
    paddingHorizontal: 32,
    width: 343,
    textAlign: "center",
    justifyContent: "center",
    alignContent: "center",
    color: "white",
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 19,
    marginTop: 19,
  },
  regButtonIf: {
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 19,
    color: "#1B4371",
    marginTop: 16,
  },
});
